### ISSUE TITLE
Compilation on VS2019

### ISSUE THREAD

**Issue by dphamminh** [sridharb1/openssl-x86_x64#1]
Dear Sridhard,

I want to develop a libssh2 library. I started to compile zlib and it worked well (I had to fine tune masm but it was OK after)

However, when I tried to compile your openssl code in VS 2019 I got a lot of errors, some in the vcx.proj files (wrong directory) as well as missing .h files.

Currently, I'm not able to fix these issues and I don't know where to start. Could you help me ?

Thank you in advance

Duc (dphamminh@orange.fr)

**Comment by sridharb1** [comment]
It has been a while since I updated this project. I know that I have recently compiled openssl (within a month?) with a fairly recent version of VS. Let me first see if there are any changed project files that I need to update. Otherwise, we will try to find out what is going on in your environment.

**Comment by sridharb1** [comment]
Today, I reconfirmed that the compile works well and with the latest openssl, 1.1.1t. I have updated project files, but that was to make them use VS2022, the latest version that I tried with.

The errors that you describe seem to be directory hierarchy issues - please ensure that you have followed the instructions for where these files have to be placed in relation to the parent openssl folder. These instructions are in the main README for the project.

**Comment by dphamminh** [comment]
Dear Sridhar,Thank you very much for your message. I had some issues regarding the perl installation (which I solved by adding perl.exe in the window path) and now it is much better.However, I'm still facing some issues with two files. Do you have any idea of how to solve the problem ?Ducprogs.pl : compiler output :1>Can't locate configdata.pm in @INC (you may need to install the configdata module) ***@***.*** contains: . ms\x64 c:/Users/Admin/AppData/Local/activestate/cache/a602d8a7/site/lib c:/Users/Admin/AppData/Local/activestate/cache/a602d8a7/lib) at C:\Users\Admin\Documents\Visual_Studio_2019\openssl\apps\progs.pl line 15.1>BEGIN failed--compilation aborted at C:\Users\Admin\Documents\Visual_Studio_2019\openssl\apps\progs.pl line 15.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for '..\..\apps\progs.pl' exited with code 2.1>Done building project "_prebuild.vcxproj" -- FAILED.========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========sha512-x86_64.pl : compiler outputBuild started...1>------ Build started: Project: libcrypto-1_1, Configuration: Debug x64 ------1>Performing Custom Build Tools1> Assembling: C:\Users\Admin\Documents\Visual_Studio_2019\openssl\build\libcrypto-1_1\x64\Debug\_work\sha512-x86_64.asm1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\crypto\sha\asm\sha512-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\sha256-x86_64.asm" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\crypto\sha\asm\sha512-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\libcrypto-1_1\sha256-x86_64.obj" has not been created. This may cause incremental build to work incorrectly.1>Done building project "libcrypto-1_1.vcxproj".========== Build: 1 succeeded, 0 failed, 0 up-to-date, 0 skipped ==========envoyé : 6 janvier 2023 à 06:48de : Sridhar Boovaraghavan ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>cc : dphamminh ***@***.***>, Author ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1) Today, I reconfirmed that the compile works well and with the latest openssl, 1.1.1t. I have updated project files, but that was to make them use VS2022, the latest version that I tried with.The errors that you describe seem to be directory hierarchy issues - please ensure that you have followed the instructions for where these files have to be placed in relation to the parent openssl folder. These instructions are in the main README for the project.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sridharb1** [comment]
Searching on the net for this issue leads me to this solution. Could you try this?

https://github.com/intel/QAT_Engine/blob/master/docs/troubleshooting.md

**Comment by dphamminh** [comment]
Dear Sridharb,In fact, I didn't had a valid configdata.pm file in my openssl directory. This was because I didn't followed the instruction to install and configure PERL and NASM... Sorry for this mistakeThe situation is much better now but the file "sha512-x86_64.pl" is still causing troubles. Below is the compiler output. All other pl files are properly compiled.Thank you very much for your help. I wish you a very nice week end.DucBuild started...1>------ Build started: Project: libcrypto-1_1, Configuration: Debug x64 ------1>Performing Custom Build Tools1> Assembling: C:\Users\Admin\Documents\Visual_Studio_2019\openssl\build\libcrypto-1_1\x64\Debug\_work\sha512-x86_64.asm1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\crypto\sha\asm\sha512-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\sha256-x86_64.asm" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\crypto\sha\asm\sha512-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\libcrypto-1_1\sha256-x86_64.obj" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\ms\uplink-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\uplink-x86_64.asm" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\ms\uplink-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\libcrypto-1_1\uplink-x86_64.obj" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\util\mkdef.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\libcrypto-1_1.def" has not been created. This may cause incremental build to work incorrectly.1>LINK : fatal error LNK1181: cannot open input file 'x64\Debug\libcrypto-1_1\sha256-x86_64.obj'1>Done building project "libcrypto-1_1.vcxproj" -- FAILED.========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========envoyé : 6 janvier 2023 à 10:25de : Sridhar Boovaraghavan ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>cc : dphamminh ***@***.***>, Author ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1) Searching on the net for this issue leads me to this solution. Could you try this?https://github.com/intel/QAT_Engine/blob/master/docs/troubleshooting.md—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dphamminh** [comment]
Dear Sridharb,In fact, I think that the problem is that asm files generated by perl are not created in the directory expected by the compiler. I will check this issue after the week end.Ducenvoyé : 6 janvier 2023 à 17:50de : Duc PHAM-MINH ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1)Dear Sridharb,In fact, I didn't had a valid configdata.pm file in my openssl directory. This was because I didn't followed the instruction to install and configure PERL and NASM... Sorry for this mistakeThe situation is much better now but the file "sha512-x86_64.pl" is still causing troubles. Below is the compiler output. All other pl files are properly compiled.Thank you very much for your help. I wish you a very nice week end.DucBuild started...1>------ Build started: Project: libcrypto-1_1, Configuration: Debug x64 ------1>Performing Custom Build Tools1> Assembling: C:\Users\Admin\Documents\Visual_Studio_2019\openssl\build\libcrypto-1_1\x64\Debug\_work\sha512-x86_64.asm1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\crypto\sha\asm\sha512-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\sha256-x86_64.asm" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\crypto\sha\asm\sha512-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\libcrypto-1_1\sha256-x86_64.obj" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\ms\uplink-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\uplink-x86_64.asm" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\ms\uplink-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\libcrypto-1_1\uplink-x86_64.obj" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\util\mkdef.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\libcrypto-1_1.def" has not been created. This may cause incremental build to work incorrectly.1>LINK : fatal error LNK1181: cannot open input file 'x64\Debug\libcrypto-1_1\sha256-x86_64.obj'1>Done building project "libcrypto-1_1.vcxproj" -- FAILED.========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========envoyé : 6 janvier 2023 à 10:25de : Sridhar Boovaraghavan ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>cc : dphamminh ***@***.***>, Author ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1) Searching on the net for this issue leads me to this solution. Could you try this?https://github.com/intel/QAT_Engine/blob/master/docs/troubleshooting.md—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dphamminh** [comment]
Dear Sridhard,I have investigated a little bit the directory issues in my compilation chain and found some weird things  regarding the asm files generation and compilation. It mainly affects lhe generation of libcrypto. I made some correction and have now a libcrypto library that I can test.Thanks a lot for your help and the work that you have done on this.Duc%%%%%%%%%%%%%1) the execution of sha512-x86_64.pl from the GUI generates sha256-x86_64.asm instead of sha512-x86_64.asm. This leads to an error in the link process because the sha512-x86_64.obj is not found. I modified the names and it is working now but the linker now detects an object declared more than once. - Is this the right way to correct this issue?2) the linker detects an object declared more than once in e_padlock.obj. - I don't know how to solve this issue.3) The perl scripts do not accept spaces in file names. I had to change Visual Studio 2019 to Visual_Studio_2019. 4) I had to run the INSTALL script to generate opensslconf.h (needed for the compilation of openssl. It also generates .asm files which seem to be ignored when using Visual Studio project files (openssl.sln). - Is there a difference between the .asm files created in command line and with the GUI ?5) When compiling the tests, the linker doesn't find the function sha256_block_data_order in libcrypto-1_1.lib(sha256.obj). In fact, the function is declared in sha256.c but not implemented- I defined an empty sha256_block_data_order and could generate the library but that solves only the linker error. The real code is missing... envoyé : 6 janvier 2023 à 18:42de : Duc PHAM-MINH ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1)Dear Sridharb,In fact, I think that the problem is that asm files generated by perl are not created in the directory expected by the compiler. I will check this issue after the week end.Ducenvoyé : 6 janvier 2023 à 17:50de : Duc PHAM-MINH ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1)Dear Sridharb,In fact, I didn't had a valid configdata.pm file in my openssl directory. This was because I didn't followed the instruction to install and configure PERL and NASM... Sorry for this mistakeThe situation is much better now but the file "sha512-x86_64.pl" is still causing troubles. Below is the compiler output. All other pl files are properly compiled.Thank you very much for your help. I wish you a very nice week end.DucBuild started...1>------ Build started: Project: libcrypto-1_1, Configuration: Debug x64 ------1>Performing Custom Build Tools1> Assembling: C:\Users\Admin\Documents\Visual_Studio_2019\openssl\build\libcrypto-1_1\x64\Debug\_work\sha512-x86_64.asm1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\crypto\sha\asm\sha512-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\sha256-x86_64.asm" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\crypto\sha\asm\sha512-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\libcrypto-1_1\sha256-x86_64.obj" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\ms\uplink-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\uplink-x86_64.asm" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\ms\uplink-x86_64.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\libcrypto-1_1\uplink-x86_64.obj" has not been created. This may cause incremental build to work incorrectly.1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): warning MSB8065: Custom build for item "..\..\util\mkdef.pl" succeeded, but specified output "c:\users\admin\documents\visual_studio_2019\openssl\build\libcrypto-1_1\x64\debug\_work\libcrypto-1_1.def" has not been created. This may cause incremental build to work incorrectly.1>LINK : fatal error LNK1181: cannot open input file 'x64\Debug\libcrypto-1_1\sha256-x86_64.obj'1>Done building project "libcrypto-1_1.vcxproj" -- FAILED.========== Build: 0 succeeded, 1 failed, 3 up-to-date, 0 skipped ==========envoyé : 6 janvier 2023 à 10:25de : Sridhar Boovaraghavan ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>cc : dphamminh ***@***.***>, Author ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1) Searching on the net for this issue leads me to this solution. Could you try this?https://github.com/intel/QAT_Engine/blob/master/docs/troubleshooting.md—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sridharb1** [comment]
Hi Duc,

The custom build command for sha512-x86_64.pl is below. 

Please see that it has two commands and they generate both sha512-x86_64.asm as well as sha256-x86_64.asm.

Are you not executing the first part?

mkdir E:\Projects\openssl\build\libcrypto-1_1\x64\Debug\_work 2>nul
set ASM=ml64
perl %(FullPath) masm E:\Projects\openssl\build\libcrypto-1_1\x64\Debug\_work\%(Filename).asm && ml64 /c /Cp /Cx /nologo /Zi /Fox64\Debug\libcrypto-1_1\%(Filename).obj E:\Projects\openssl\build\libcrypto-1_1\x64\Debug\_work\%(Filename).asm
perl %(FullPath) masm E:\Projects\openssl\build\libcrypto-1_1\x64\Debug\_work\sha256-x86_64.asm && ml64 /c /Cp /Cx /nologo /Zi /Fox64\Debug\libcrypto-1_1\sha256-x86_64.obj E:\Projects\openssl\build\libcrypto-1_1\x64\Debug\_work\sha256-x86_64.asm

**Comment by sridharb1** [comment]
Regarding needing to declare functions etc., no it should not be the case.

Also, you don't have to generate opensslconf.h. It is already provided in the project. Please see that there are two versions opensslconf.x64.h and .x86.h. A custom build command will rename the appropriate opensslconf.xNN.h to opensslconf.h depending on the build's platform/configuration chosen (for eg Debug/x64). Please see the _prebuild project for more details.

I am surprised with the problems of spaces - most VS installations contain spaces in them. Perhaps fix the above issue and see if solves more things.

**Comment by dphamminh** [comment]
Dear Sridharb,Sorry for the late response. It took me a while to find out the problem on sha512-x86_64.Finally, I found out that the custom build command must be structured with CR instead of white space (on my computer):mkdir $(OutDir)_work 2>nulset ASM=ml64 $(PERL) %(FullPath) masm $(OutDir)_work\%(FileName).asm && ml64 /c /Cp /Cx /nologo /Zi /Fo$(IntDir)%(FileName).obj $(OutDir)_work\%(FileName).asm $(PERL) %(FullPath) masm $(OutDir)_work\sha256-x86_64.asm && ml64 /c /Cp /Cx /nologo /Zi /Fo$(IntDir)sha256-x86_64.obj $(OutDir)_work\sha256-x86_64.asmThere was a white space after set ASM=ml64 and this caused the non generation of sha512-x86_64.asmOn the other white space issue, I confirm that on my computer, there is a problem when installing the openssl package in "Visual Studio 2019". PERL gets lost and sees only "Visual" and cannot open it. I also switched Windows to english and it solved issues in Visual Studio !The good thing is that I am now ready to test the libssh2 library. :-)Many thanks for your support and the great work. Ducenvoyé : 12 janvier 2023 à 05:16de : Sridhar Boovaraghavan ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>cc : dphamminh ***@***.***>, Author ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1) Regarding needing to declare functions etc., no it should not be the case.I am surprised with the problems of spaces - most VS installations contain spaces in them. Perhaps fix the above issue and see if solves more things.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sridharb1** [comment]
Please clarify what do you mean by installing the openssl package in Visual Studio 2019?

**Comment by dphamminh** [comment]
Dear Sridharb,I'm currently trying to control a remote switch via SSH. The switch is a small device which has been upgraded to have a linux OS (openwrt). My objective is to use the SSH library in a custom program that I will develop in C++.I have no security issues and would have preferred to use Telnet, but the switch doesn't support it. I looking in that direction as well (Telnet on the switch and in my program)Kind regardsDucenvoyé : 17 janvier 2023 à 05:04de : Sridhar Boovaraghavan ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>cc : dphamminh ***@***.***>, Author ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1) Please clarify what do you mean by installing the openssl package in Visual Studio 2019?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by dphamminh** [comment]
Dear SridharbI probably not answered your question properly...In fact, I have two computers with Visual Studio 2019 and wanted to avoid having two different versions of Visual Studio. (One computer has to stay with visual studio 2019). So I retargeted the solution that you have developped and recompiled every thing. It worked well but finally, I decided to switch to VS 2022 to be on the safe side and hope that the library will work on both.Ducenvoyé : 18 janvier 2023 à 19:57de : Duc PHAM-MINH ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1)Dear Sridharb,I'm currently trying to control a remote switch via SSH. The switch is a small device which has been upgraded to have a linux OS (openwrt). My objective is to use the SSH library in a custom program that I will develop in C++.I have no security issues and would have preferred to use Telnet, but the switch doesn't support it. I looking in that direction as well (Telnet on the switch and in my program)Kind regardsDucenvoyé : 17 janvier 2023 à 05:04de : Sridhar Boovaraghavan ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>cc : dphamminh ***@***.***>, Author ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1) Please clarify what do you mean by installing the openssl package in Visual Studio 2019?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sridharb1** [comment]
Yes, it should work well with VS 2019 with minimal changes. All the best. If you think appropriate, I will close this issue.

**Comment by dphamminh** [comment]
Dear Sridhard,Yes you can close the case. Every thing is working now and I could test a full SSH connection with the examples. In fact, the main problem was linked to OS language issues which affects the behavior of PERL and Visual Studio. I switched from french to english and it solved these issues. I solved the "space" issue by using underscores but this might be not necessary now.Many thanks for your help and your great job in maintaining this libraries.Ducenvoyé : 19 janvier 2023 à 06:02de : Sridhar Boovaraghavan ***@***.***>à : sridharb1/openssl-x86_x64 ***@***.***>cc : dphamminh ***@***.***>, Author ***@***.***>objet : Re: [sridharb1/openssl-x86_x64] Compilation on VS2019 (Issue #1) Yes, it should work well with VS 2019 with minimal changes. All the best. If you think appropriate, I will close this issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
